#!/bin/bash
VERSION=`cat PACKAGE_VERSION`
PACKAGE_ARCHIVE="dist/metadatautilspkg-$VERSION"".tar.gz"
PACKAGE_DIR="metadatautilspkg-$VERSION"

tar -xvf $PACKAGE_ARCHIVE
cp PACKAGE_VERSION $PACKAGE_DIR
cd $PACKAGE_DIR
python3 setup.py install

cd ..

rm -rf $PACKAGE_DIR

# changes made for issue # 7
cp config/dbconf-template.json config/dbconf.json

echo ****************************************************
echo Please add your DB connection credentials in the file "config/dbconf.json".
echo ****************************************************